version: '2'
services:
  server:
    image: s4dx/assembly_server:latest
    command: headless:=true task:=screwing
    environment:
      - ROS_HOSTNAME=server
    networks:
      - rosnet

  usercode:
    image: s4dx/assembly_screw_example:latest
    command: --wait assembly_example assembly_screw.launch
    environment:
      - ROS_HOSTNAME=usercode
      - ROS_MASTER_URI=http://server:11311 
    depends_on:
      - server
    networks:
      - rosnet

networks:
  rosnet:
