version: '2'
services:
  server:
    image: s4dx/assembly_server:latest
    command: task:=plugging
    environment:
      - ROS_HOSTNAME=server
    networks:
      - rosnet

  usercode:
    image: s4dx/assembly_plugging_example:latest
    environment:
      - ROS_HOSTNAME=usercode
      - ROS_MASTER_URI=http://server:11311 
    depends_on:
      - server
    networks:
      - rosnet

networks:
  rosnet:
